### ISSUE TITLE
NuGet package workflow

### ISSUE THREAD

**Issue by ricardoboss** [trenz-gmbh/TRENZ.Lib.RazorMail#5]
We should add a workflow that automatically publishes a new nuget when a version is tagged via git.

**Comment by chucker** [comment]
Bummer Sharpliner doesn't yet support GitHub properly.

**Comment by ricardoboss** [comment]
TBF GitHub Actions are way easier to maintain than Azure Pipelines...

**Comment by chucker** [comment]
This is probably moot with #27.

**Comment by ricardoboss** [comment]
For now at least
